name: CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up private key for SSH
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_PRIVATE_KEY" > ~/.ssh/fastapi_key.pem
          chmod 600 ~/.ssh/fastapi_key.pem
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/fastapi_key.pem
          echo -e "Host *\n\tStrictHostKeyChecking no\n\t" > ~/.ssh/config
        env:
          EC2_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/fastapi_key.pem ubuntu@ec2-52-32-33-216.us-west-2.compute.amazonaws.com << 'EOF'
            cd ~/fastapi-book-project-2
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart fastapi.service
          EOF

