name: CD Pipeline

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up private key for SSH
        run: |
          echo "$PRIVATE_KEY" > private-key.pem
          chmod 600 private-key.pem

      - name: Deploy to EC2
        run: |
          ssh -i private-key.pem ubuntu@ec2-52-32-33-216.us-west-2.compute.amazonaws.com << 'EOF'
            cd ~/fastapi-book-project-2
            git pull origin main  
            source venv/bin/activate 
            pip install -r requirements.txt  
            sudo systemctl restart fastapi.service 
          EOF
        env:
          PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
